// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgOB3tM4h8wfftfSR0zpEXxK2jG5bngY',
    appId: '1:488213739744:web:c9ddf3725e6d0bfa443885',
    messagingSenderId: '488213739744',
    projectId: 'aptech-project-c6558',
    authDomain: 'aptech-project-c6558.firebaseapp.com',
    storageBucket: 'aptech-project-c6558.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK25eUpoxjnMfCk3lzr_laZKLJBj_1kro',
    appId: '1:488213739744:android:d84b0d7b621e8b6f443885',
    messagingSenderId: '488213739744',
    projectId: 'aptech-project-c6558',
    storageBucket: 'aptech-project-c6558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFgP5QzAWyJ1pAOwUMgUD8t00Bbfa6UQ',
    appId: '1:488213739744:ios:154a05c9e400057c443885',
    messagingSenderId: '488213739744',
    projectId: 'aptech-project-c6558',
    storageBucket: 'aptech-project-c6558.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
